// Self-check for utils/lds.ts — run with `npm run check:lds`.
//
// Two halves:
//   1. CQL + address ranking, ported from the Python reference's self-check.
//   2. Geometry, which is NOT a port — it replaces shapely, so every expected
//      value below was generated by shapely itself and pasted in. covers()
//      semantics are the whole point: the boundary of a polygon AND the
//      boundary of a hole both count as covered.
import assert from 'node:assert/strict';
import {
    bboxOf, centroidOf, containsPoint, cqlBbox, cqlLike, cqlQuote, featuresWithin,
    ownerNameCql, score, streetNumber, searchAddress, type LDSClient, type GeoJsonGeometry,
} from './lds.ts';

// --------------------------------------------------------------------------- //
// Address ranking
// --------------------------------------------------------------------------- //

assert.equal(streetNumber('19 Carroll Street, Dunedin'), '19');
assert.equal(streetNumber('119 Carroll Street, Dunedin Central'), '119');
assert.equal(streetNumber('K/810 Great South Road, Penrose'), '810');
assert.equal(streetNumber('1A/342 Oriental Parade, Oriental Bay'), '342');
assert.equal(streetNumber('19A Rimu Road'), '19a');
assert.equal(streetNumber('Carroll Street, Dunedin'), null);

const best = (query: string, candidates: string[]): string =>
    candidates.reduce((a, b) => {
        const sa = score(query, a), sb = score(query, b);
        return (sb[0] - sa[0] || sb[1] - sa[1]) > 0 ? b : a;
    });

// The bug a plain LIKE causes: '19' is a substring of '119'.
assert.equal(best('19 Carroll Street, Dunedin', [
    '119 Carroll Street, Dunedin Central, Dunedin',
    '19 Carroll Street, Dunedin Central, Dunedin',
]), '19 Carroll Street, Dunedin Central, Dunedin');

// A unit prefix on the candidate must not hide the street number.
assert.equal(best('810 Great South Road, Penrose, Auckland', [
    '1810 Great South Road, Manukau, Auckland',
    'K/810 Great South Road, Penrose, Auckland',
]), 'K/810 Great South Road, Penrose, Auckland');

// With no number in the query, ranking falls back to token coverage.
assert.equal(best('Oriental Parade, Oriental Bay', [
    '12 Hobson Street, Thorndon, Wellington',
    '242 Oriental Parade, Oriental Bay, Wellington',
]), '242 Oriental Parade, Oriental Bay, Wellington');

// --------------------------------------------------------------------------- //
// Owner name CQL
// --------------------------------------------------------------------------- //

// A full name must be split: LDS holds surname and other names apart, so
// matching "joshua wong" against either column alone finds nothing.
const cql = ownerNameCql('joshua wong');
assert.ok(cql.includes("prime_surname ILIKE '%wong%' AND prime_other_names ILIKE '%joshua%'"));
// ...and the reverse order must work too.
assert.ok(cql.includes("prime_surname ILIKE '%joshua%' AND prime_other_names ILIKE '%wong%'"));
const count = (s: string, ch: string) => s.split(ch).length - 1;
assert.equal(count(cql, '('), count(cql, ')'), 'unbalanced parens would 400 at LDS');

// Three tokens, surname at either end.
const three = ownerNameCql('en qi lim');
assert.ok(three.includes("prime_surname ILIKE '%lim%' AND prime_other_names ILIKE '%en qi%'"));
assert.equal(count(ownerNameCql('lim en qi'), '('), count(three, '('));

// A single token searches every name column, not just the surname.
const one = ownerNameCql('wong');
for (const column of ['corporate_name', 'prime_surname', 'prime_other_names']) {
    assert.ok(one.includes(`${column} ILIKE '%wong%'`), `${column} not searched`);
}
assert.ok(!one.includes(' AND '), 'a single token has nothing to AND against');

// Companies still match on the whole string.
assert.ok(ownerNameCql('Norak Properties Limited')
    .includes("corporate_name ILIKE '%Norak Properties Limited%'"));

// Quotes are escaped, or the filter breaks at the server.
assert.ok(ownerNameCql("O'Brien").includes("O''Brien"));

// --------------------------------------------------------------------------- //
// CQL escaping — this is a trust boundary: the query string is user input.
// --------------------------------------------------------------------------- //

assert.equal(cqlQuote("O'Brien"), "'O''Brien'");
// A user's own wildcards must not widen the search.
assert.equal(cqlLike('full_address', '100%_x'), "full_address ILIKE '%100\\%\\_x%'");
// An attempt to break out of the literal stays inside it.
assert.equal(cqlLike('corporate_name', "' OR 1=1 --"),
    "corporate_name ILIKE '%'' OR 1=1 --%'");
// bbox argument order is (miny, minx, maxy, maxx) — swapped vs the call.
assert.equal(cqlBbox(1, 2, 3, 4), 'bbox(shape,2,1,4,3)');

// --------------------------------------------------------------------------- //
// Geometry — expected values all produced by shapely.
// --------------------------------------------------------------------------- //

const donut: GeoJsonGeometry = {
    type: 'Polygon',
    coordinates: [
        [[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]],
        [[4, 4], [6, 4], [6, 6], [4, 6], [4, 4]],
    ],
};
const multi: GeoJsonGeometry = {
    type: 'MultiPolygon',
    coordinates: [
        [[[0, 0], [2, 0], [2, 2], [0, 2], [0, 0]]],
        [[[10, 10], [14, 10], [14, 14], [10, 14], [10, 10]]],
    ],
};
// An L-shape: the area centroid (2.2) is nowhere near the vertex mean (2.67),
// so this fails loudly if centroidOf ever degrades to averaging coordinates.
const ell: GeoJsonGeometry = {
    type: 'Polygon',
    coordinates: [[[0, 0], [6, 0], [6, 2], [2, 2], [2, 6], [0, 6], [0, 0]]],
};
// Realistic NZ-scale parcel in lon/lat degrees, to check float behaviour.
const parcel: GeoJsonGeometry = {
    type: 'Polygon',
    coordinates: [[
        [174.8151, -36.9121], [174.8156, -36.9121],
        [174.8156, -36.9126], [174.8151, -36.9126], [174.8151, -36.9121],
    ]],
};

const near = (actual: number, expected: number, what: string) =>
    assert.ok(Math.abs(actual - expected) < 1e-9,
        `${what}: got ${actual}, want ${expected}`);

// bounds
assert.deepEqual(bboxOf(donut), [0, 0, 10, 10]);
assert.deepEqual(bboxOf(multi), [0, 0, 14, 14]);
assert.deepEqual(bboxOf(parcel), [174.8151, -36.9126, 174.8156, -36.9121]);

// centroid, vs shapely
near(centroidOf(donut)[0], 5.0, 'donut centroid x');
near(centroidOf(donut)[1], 5.0, 'donut centroid y');
near(centroidOf(multi)[0], 9.8, 'multi centroid x');
near(centroidOf(multi)[1], 9.8, 'multi centroid y');
near(centroidOf(ell)[0], 2.2, 'L-shape centroid x (area, not vertex mean)');
near(centroidOf(ell)[1], 2.2, 'L-shape centroid y (area, not vertex mean)');
near(centroidOf(parcel)[0], 174.81534999999997, 'parcel centroid x');
near(centroidOf(parcel)[1], -36.912349999999996, 'parcel centroid y');
assert.deepEqual(centroidOf({ type: 'Point', coordinates: [1.5, -2.5] }), [1.5, -2.5]);

// covers() truth table, straight from shapely
const coversCases: [GeoJsonGeometry, number, number, boolean, string][] = [
    [donut, 5, 5, false, 'centre of the hole'],
    [donut, 5, 4, true, "on the hole's edge"],
    [donut, 1, 1, true, 'solid material'],
    [donut, 0, 0, true, 'outer corner'],
    [donut, 0, 5, true, 'on the outer edge'],
    [donut, 10, 5, true, 'on the far outer edge'],
    [donut, -0.5, 5, false, 'outside'],
    [donut, 4, 4, true, 'hole corner'],
    [donut, 5.999999999, 5, false, 'just inside the hole, 1e-9 off the edge'],
    [multi, 1, 1, true, 'inside first part'],
    [multi, 12, 12, true, 'inside second part'],
    [multi, 5, 5, false, 'in the gap between parts'],
    [multi, 2, 2, true, 'corner of first part'],
    [parcel, 174.81535, -36.91235, true, 'inside parcel'],
    [parcel, 174.8151, -36.91235, true, 'on parcel west edge'],
    [parcel, 174.8160, -36.91235, false, 'east of parcel'],
];
for (const [geom, x, y, want, why] of coversCases) {
    assert.equal(containsPoint(geom, x, y), want,
        `containsPoint(${x}, ${y}) should be ${want} — ${why}`);
}

// featuresWithin keeps only the address points the title polygon covers.
const kept = featuresWithin(donut, [
    { geometry: { type: 'Point', coordinates: [1, 1] }, properties: { full_address: 'in' } },
    { geometry: { type: 'Point', coordinates: [5, 5] }, properties: { full_address: 'in hole' } },
    { geometry: { type: 'Point', coordinates: [99, 99] }, properties: { full_address: 'far' } },
    { geometry: null, properties: { full_address: 'no geometry' } },
]);
assert.deepEqual(kept.map(f => f.properties?.full_address), ['in']);

console.log('ok - CQL, address ranking and geometry self-checks passed');

// Pasted postal addresses: street fallback must preserve locality/number and
// request a choice when still ambiguous. No external requests in these tests.
const postalQuery = '810 Great South Road, Penrose, Auckland 1061';
const candidate = (number = '810', suburb = 'Penrose', city = 'Auckland') => ({
    geometry: null, properties: { full_address: `${number} Great South Road`, suburb_locality: suburb, town_city: city },
});
const lookup = async (matches: ReturnType<typeof candidate>[]) => {
    let calls = 0;
    const client = { getFeatures: async () => ++calls === 1 ? [] : matches } as unknown as LDSClient;
    return searchAddress(client, postalQuery);
};
assert.equal((await lookup([candidate()])).resolution_status, 'no_geometry');
for (const wrong of [candidate('1810'), candidate('810', 'Otahuhu'), candidate('810', 'Penrose', 'Wellington')]) {
    assert.equal((await lookup([wrong])).resolution_status, 'not_found');
}
assert.equal((await lookup([candidate(), candidate()])).resolution_status, 'needs_confirmation');
console.log('ok - full postal address, locality/number isolation and ambiguous selection');
